Fixed org.nuxeo.runtime.server.enabled=true otherwise the shell cannot connect to the repository.
java.lang.reflect.UndeclaredThrowableException
	at $Proxy11.getProperties(Unknown Source)
	at org.nuxeo.runtime.config.Configuration.load(Configuration.java:206)
	at org.nuxeo.runtime.config.AutoConfigurationService.loadCompat(AutoConfigurationService.java:111)
	at org.nuxeo.runtime.config.AutoConfigurationService.load(AutoConfigurationService.java:92)
	at org.nuxeo.ecm.core.client.NuxeoClient.doConnect(NuxeoClient.java:155)
	at org.nuxeo.ecm.core.client.NuxeoClient.connect(NuxeoClient.java:107)
	at org.nuxeo.ecm.shell.CommandContext.initalizeConnection(CommandContext.java:222)
	at org.nuxeo.ecm.shell.CommandContext.getRepositoryInstance(CommandContext.java:188)
	at org.nuxeo.ecm.shell.commands.repository.ListCommand.run(ListCommand.java:40)
	at org.nuxeo.ecm.shell.CommandLineService.runCommand(CommandLineService.java:317)
	at org.nuxeo.ecm.shell.commands.InteractiveCommand.runCommand(InteractiveCommand.java:132)
	at org.nuxeo.ecm.shell.commands.InteractiveCommand.processInput(InteractiveCommand.java:116)
	at org.nuxeo.ecm.shell.commands.InteractiveCommand.run(InteractiveCommand.java:96)
	at org.nuxeo.ecm.shell.CommandLineService.runCommand(CommandLineService.java:317)
	at org.nuxeo.ecm.shell.Main.main(Main.java:101)
	at org.nuxeo.ecm.shell.CommandLineService$1.run(CommandLineService.java:345)
	at org.nuxeo.osgi.application.StandaloneApplication.main(StandaloneApplication.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.nuxeo.osgi.application.Main.main(Main.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.nuxeo.runtime.launcher.Main.main(Main.java:83)
Caused by: java.rmi.MarshalException: Failed to communicate.  Problem during marshalling/unmarshalling; nested exception is:
	java.net.SocketException: end of file
	at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:127)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:699)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:122)
	at org.jboss.remoting.Client.invoke(Client.java:1634)
	at org.jboss.remoting.Client.invoke(Client.java:548)
	at org.jboss.remoting.Client.invoke(Client.java:536)
	at org.nuxeo.runtime.remoting.transporter.TransporterClient.invoke(TransporterClient.java:238)
	... 27 more
Caused by: java.net.SocketException: end of file
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:624)
	... 32 more